### PR TITLE
[WIP] Introduce AWS IAM authentication

### LINKED ISSUE #218: Kafka Login with IAM policy
Hello, 

I would like to connect with AWS MSK with IAM. 

Does it possible

### PR DESCRIPTION
**Pull request by lomluca**
AWS MSK provides a custom authentication method that is fully integrated with AWS IAM: https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

This auth method has a big advantage for AWS customers: it allows to manage auth/authz with IAM policies.

I implemented a new `sarama.SCRAMClient` based on the [library developed by AWS](https://github.com/aws/aws-msk-iam-auth) to provide IAM auth for Java applications. The ["Details" section](https://github.com/aws/aws-msk-iam-auth#details) in the README helped me to understand better how to build the payload during SASL workflow.

Closes #218

### CODE REVIEW

**Comment by lomluca** [comment]
At the moment Sarama seems not really flexible in supporting custom SASL/SCRAM mechanisms (such as `AWS_MSK_IAM` in this case). We are discussing here about this issue: https://github.com/Shopify/sarama/pull/2192

Once the upstream issue is solved, we can go with this new feature.

**Comment by ehlomarcus** [comment]
It would be fantastic to get this implemented 👍

**Comment by simonkarman** [comment]
@lomluca Any progress on the implementation? Can I help out?

**Comment by RaphaelDucay** [comment]
Hello @lomluca @Mongey :)  Any plan releasing this feature soon ? I would be really interested on my side aswell ! Thanks in advance !

**Comment by GediminasSimkus** [comment]
Tried this PR, but it looks that it's not completed. I'm getting an error: `kafka: invalid configuration (The SASL mechanism configuration is invalid. Possible values are `OAUTHBEARER`, `PLAIN`, `SCRAM-SHA-256`, `SCRAM-SHA-512` and `GSSAPI`)` when trying to use it along with passing `sasl_aws_region` parameters via provider.

**Comment by GediminasSimkus** [comment]
Tried this PR, but it looks that it's not completed. I'm getting an error: `kafka: invalid configuration (The SASL mechanism configuration is invalid. Possible values are `OAUTHBEARER`, `PLAIN`, `SCRAM-SHA-256`, `SCRAM-SHA-512` and `GSSAPI`)` when trying to use it along with passing `sasl_aws_region` parameter via provider. Or someone else has better luck than me with IAM auth?

**Comment by jgraeve** [comment]
It would be fantastic to get this implemented 👍

**Comment by joaocc** [comment]
Hi. Are there any news on this PR? It seems that the upstream PR mentioned above is pending non-tech steps. Thanks!

**Comment by joaocc** [comment]
It seems the upstream issue has been changed to https://github.com/IBM/sarama/pull/2482. Just adding here for reference.

**Comment by olivd4400** [comment]
any update on this?

**Comment by mattiasnensen** [comment]
Any update on this?

**Comment by Mongey** [comment]
The update is that I'm waiting for  https://github.com/IBM/sarama/pull/2482 to land in sarama.

Alternatively, I could use the fork of sarama, but I'd want some way to test that the PR works against AWS MSK.

**Comment by dnwe** [comment]
@Mongey you might also be interesting in the new https://github.com/aws/aws-msk-iam-sasl-signer-go library from AWS for this

**Comment by olivd4400** [comment]
seems that the PR https://github.com/IBM/sarama/pull/2482 has been closed because of availability of IAM authentication in non-JVM languages including go (https://github.com/aws/aws-msk-iam-sasl-signer-go)

**Comment by cemo** [comment]
We have another pr #372 which pretty much same with less code.

**Comment by Mongey** [comment]
superseded by #372

**Pull request closed without merging**
