### PR TITLE
Add ACL cache and debouncing request queues for creation/deletion requests to make parallelism useful

### PR DESCRIPTION
**Pull request by eh-steve**
When creating/destroying 1000 ACLs:

#### Provides a 780% speedup for ACL creations and 1470% speedup for ACL deletions .

Before:
```shell
time terraform apply -auto-approve -parallelism=1000 
25.98s user 18.43s system 83% cpu 53.286 total

time terraform destroy -parallelism=1000 -auto-approve  
39.98s user 19.88s system 32% cpu 3:04.59 total

```

After:
```shell
time terraform apply -parallelism=1000 -auto-approve
25.81s user 15.20s system 603% cpu 6.798 total

time terraform destroy -parallelism=1000 -auto-approve 
30.12s user 13.22s system 344% cpu 12.570 total
```

For anyone facing the same issue, I've published a release here until this PR is reviewed/merged:
https://registry.terraform.io/providers/eh-steve/kafka/latest

### CODE REVIEW

**Comment by eh-steve** [comment]
Not sure if the CI failures are legit, as I have tests passing locally...?

**Comment by SanchosPancho** [comment]
I've test your PR and seems something wrong with it. After plan I've got an error:
```

│ Error: kafka: client has run out of available brokers to talk to: 5 errors occurred:
│ 	* EOF
│ 	* EOF
│ 	* EOF
│ 	* EOF
│ 	* EOF
```

Without this patch all works good

**Comment by SanchosPancho** [comment]
@eh-steve I've try it on real cluster, but I think that depends on kafka version, I've fail on old 2.3+ kafka cluster

**Comment by eh-steve** [comment]
Yeah I guess if you wanted to test this PR you could locally cherry pick the first commit onto an older master.

I've also released it in the registry under `eh-steve/kafka` version 0.5.5 so you could test with that. The parent master commit for that release is 993494b, which may have already introduced the problem though?

**Comment by akaltsikis** [comment]
Hey @eh-steve , Thanks for the above optimizations. Does the above reduce the time execution, on regular terraform plan commands for clusters that have tons of ACLs ?

BTW is there any help you need, to push forward with this PR?

**Comment by eh-steve** [comment]
> Hey @eh-steve , Thanks for the above optimizations. Does the above reduce the time execution, on regular terraform plan commands for clusters that have tons of ACLs ?

Yeah it should 


> BTW is there any help you need, to push forward with this PR?

Just waiting for an approval and a CI run

**Comment by eh-steve** [comment]
Hi @Mongey, thanks for the run, I can’t reproduce these CI failures locally and one of them seems to be related to GPG? Is master CI passing?

**Comment by Mongey** [comment]
hey @eh-steve thanks for the PR! looks great!
The build snapshots never really works for PR's due to GPG, I generally just ignore that failure. 

I pulled the branch down locally and tested -- it seems to work for me. 
Not sure what's going on with CI - it is quite flakey

**Pull request merged**
