### PR TITLE
[#53] Update replication.factor inplace

### PR DESCRIPTION
**Pull request by SahilKang**
This allows a topic's `replication.factor` to be updated without forcing a recreate.

### CODE REVIEW

**Comment by SahilKang** [comment]
I think this PR's ready for some :eyes: so I've lifted the WIP flag.

I'm thinking about pushing up another commit regarding the change from [2.1 to 2.4](https://github.com/Mongey/terraform-provider-kafka/pull/148/files#diff-599716d13f538e7c588fd3292bda1f3b943c06c88917fde07c5de1336e4ced53R31). Ideally, I'd like to leave the default to 2.1 and allow users the opportunity to specify 2.4 if they'd like to use :sparkles: newer features :sparkles:

This is a pretty big diff so it may be easier to review commit-by-commit instead of all at once

**Comment by SahilKang** [comment]
Hey @Mongey, I ended up keeping the updated `sarama.V2_4_0_0`, but I probe the brokers now to see if they support changing a topic's replication.factor (the broker needs to be at least version 2.4.0). If so, the provider will make the change in-place; otherwise, I kept the current behavior of [forcing a new resource](https://github.com/Mongey/terraform-provider-kafka/pull/148/commits/9c7309c70f60c445d9cfdfd0a0ba8738104e599b#diff-82a797511792f07b7f3739b5dbeaf5c56a6da763632088e35d10fdb40da34ae8R308-R310).

**Comment by cojamac** [comment]
@SahilKang I believe this work is relevant to a problem I encountered yesterday. https://github.com/Mongey/terraform-provider-kafka/issues/157

I'm wondering if there is an easy solution where (if supported) the `ReplicaCount` function might return `0, nil` when it encountered inconsistent replica counts across partitions. I believe this would result in all the partitions going through your reassignment code and this would more or less resolve the "bonus replica" problem.

https://github.com/Mongey/terraform-provider-kafka/blob/f188c53e3581901a106c8983b72e663994bffb59/kafka/topic.go#L27-L47

**Comment by toyota790** [comment]
I am wondering that is there any progress or plan for this PR? Thanks!

**Comment by SahilKang** [comment]
@cojamac I can't update the `ReplicaCount` function as you suggest because it's used by the `ReadTopic` function, which is used throughout the provider code. However, I should be able to update the replica-assignment code to handle extra/missing replicas across partitions more elegantly. Extra/missing replicas across partitions isn't really a problem for the replica-reassignment code since it can change the replica count for a partition to the correct value if a mismatch is encountered.

I am interested in how you got in this situation, though :smile:
I think the entire kafka api assumes that a topic's replica count is the same across all of its partitions, _except_ the [reassignment function](https://kafka.apache.org/protocol#The_Messages_AlterPartitionReassignments) we're using here.

@toyota790 I think I just need to rebase this against the latest changes on master. I'll give that a shot this weekend and will try pinging the maintainer again afterwards.

**Comment by toyota790** [comment]
@SahilKang Great to hear that and thank you so much! 😄

**Comment by SahilKang** [comment]
@cojamac Looking through the replica reassignment code, it looks like each partition's replication factor is already being [updated separately](https://github.com/Mongey/terraform-provider-kafka/blob/373cd75ed232482d04e138c36873fd44decf29b7/kafka/client.go#L325) so unless `ReadTopic` is called beforehand for some reason, I think the provider will correct your mismatched replica counts if you change the replication factor. I'd recommend trying to increase the `replication_factor` with the provider by 1 and then lowering it back to what you actually want, or vice-versa.

@Mongey I rebased against master and the tests are passing :tada:
The structure of the PR is similar to before, though I squashed a few commits to make things less noisy.
I also added [this commit](https://github.com/Mongey/terraform-provider-kafka/pull/148/commits/373cd75ed232482d04e138c36873fd44decf29b7) which removes some test code that was already failing on master (more info in the commit message).

**Comment by cojamac** [comment]
@SahilKang We have addressed the replica manually some time ago but I do really appreciate your contributions here. Thank you!

**Comment by Mongey** [comment]
Thanks for the great contribution @SahilKang, this looks great.

**Comment by wiegandf** [comment]
@Mongey is there any rough time frame when this is gonna be released?

**Pull request merged**
