### PR TITLE
Adding a website folder for the documentation to following normal convention

### LINKED ISSUE #74: Documentation
Hi @Mongey 

Would you accept a PR that also added the docs in a website folder structure to mirror that of other Terraform providers?

This would help us generate a Pulumi provider based off the structure :)

Paul

### PR DESCRIPTION
**Pull request by stack72**
Closes #74

### CODE REVIEW

**Comment by stack72** [comment]
@Mongey thoughts on this?

**Comment by Mongey** [comment]
LGTM... was this automated? how do I regenerate it?

**Comment by stack72** [comment]
@Mongey fraid not - this was written the same was as the HC docs are, by hand... :( I will keep an eye on this as I will be using this provider to keep pulumi-kafka up to date! So I will pitch in

**Comment by Mongey** [comment]
Thought there might be something by now 😅  Cheers!

**Pull request merged**
