### PR TITLE
Add support for importing kafka_acl resources

### PR DESCRIPTION
**Pull request by petoju**
Importer is set in a way, that if we can reconstruct the data just from
Id(), we may just use it.

This PR accomplishes that.
It also adds documentation on how to do import and reorders fields to
match the import format - so that one won't be confused so easily.

### CODE REVIEW

**Comment by petoju** [comment]
Note: this would address https://github.com/Mongey/terraform-provider-kafka/issues/151

**Comment by petoju** [comment]
Note: the tests are failing because we cannot contact Kafka brokers. I don't believe that is related to my PR (feel free to object / point out how I could break it).

**Comment by Mongey** [comment]
@petoju we should use a custom import function rather than setting this in the aclInfo function.

```
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},

**Comment by petoju** [comment]
@Mongey is there anything more custom import function would provide compared to what it provides with this change? I would like to avoid reimplementing the same thing we have now.

I believe a well-behaved TF provider, that can recover the state from ID should do it. There is another question, whether I used the correct place and whether it will affect something else.

**Comment by Mongey** [comment]
@petoju 
>  is there anything more custom import function would provide compared to what it provides with this change? I would like to avoid reimplementing the same thing we have now.

There's nothing more that the dedicated function should do, I'm just concerned about doing this in the `aclInfo` func. We call aclInfo in many places, and having it modify the state, when we don't expect it would be surprising.

**Comment by petoju** [comment]
@Mongey agreed -  I implemented it separately. Hopefully it will work like that.

**Comment by fl-max** [comment]
I see this didn't come with the latest (0.2.12) release. Are there development reasons that this is being held back?

**Pull request merged**
