### PR TITLE
Support resource_pattern_type_filter

### PR DESCRIPTION
**Pull request by Mongey**
Should address #38

### CODE REVIEW

**Comment by Mongey** [comment]
:wave: @dmazhar-cogniance If you want to try this out, you can grab the binary (for linux) from CI @ 
https://256-103748731-gh.circle-artifacts.com/0/terraform-provider-kafka

Not exactly sure how to write kafka acl's, but a quick run of this config seemed to work

```hcl
resource "kafka_acl" "test" {
   resource_name                = "syslog*"
   resource_type                = "Topic"
   resource_pattern_type_filter = "prefixed"
   acl_principal                = "User:Alice"
   acl_host                     = "*"
   acl_operation                = "Write"
   acl_permission_type          = "Allow"
 }
```

**Comment by dmazhar-cogniance** [comment]
Hi! Thanks for such a quick reaction :)
I tested the CI build, a little. The ACL is created as a charm, but looks like there is a problem with deleting the created ACLs. When I'm removing the ACL from terraform code it is not deleting from kafka. If I'm changing it terraform is marking ACL to recreate (`-/+`), creating new one, but not deleting the old ACL.

**Comment by dmazhar-cogniance** [comment]
It looks like the ACLs are not deleted still. Not sure regarding sarama, but `kafka-acls.sh` (from kafka distributions) requires the `--resource-pattern-type prefixed` parameter when deleting the ACLs. Could it be the cause of the issue?

**Comment by Mongey** [comment]
😅 Whoops, looks like I was sending `v0` requests for {Delete,Describe}ACLs.

**Comment by Mongey** [comment]
🙌 Great, I'll merge once I figure out the whole Kafka v1 / v2 compatibility 😄

**Comment by Mongey** [comment]
Went with a slightly different approach over in #50

**Pull request closed without merging**
