### PR TITLE
fix: aclRead does not read PatternType of acl already in Kafka

### PR DESCRIPTION
**Pull request by parnigot**
This is related to my issue #285 - disclaimer: I'm not really a go/terraform dev

Digging around the code I've discovered that the method `aclRead` does not set the `PatternType` (`Literal`, `Prefix`, ...) for the acls returned by kafka (maybe it's intentional? i don't know, looks wrong to me).
In the sample manifest from my issue, the ACL from Kafka (`aclID.String()`) is serialized to the following string:
```
User:CN=user|192.168.1.2|Read|Allow|Topic|test_topic|
```
While the ACL read from the state (`a.String()`) is: 
```
User:CN=user|192.168.1.2|Read|Allow|Topic|test_topic|Literal
```
Because of this, when comparing the two acls, the `exact match` [check](https://github.com/Mongey/terraform-provider-kafka/blob/55b7619d34970cc8a46b59aa8a6114a79312b82e/kafka/resource_kafka_acl.go#L132) is never true and the method falls back to the partial match code below. The partial match[¹] considers two acls with just `Principal` and `Operation` equal and in my case it swaps the two ACLs with different `Hosts`.

This PR adds the missing field to the acl from kafka so that two identical ACLs are detected.

[¹] tbh i don't understand why the partial match section exists...

### CODE REVIEW

**Comment by jkemming** [comment]
What's the status on this? Seems like the linter is complaining about an unused function, but that should be an easy fix.

**Comment by parnigot** [comment]
My bad on leaving the push request open with a failing test, I pushed my second commit in a hurry while leaving the office and didn't have time to look at it since then. Now I've removed the unused function and it should pass the lint step (waiting for the gh action to run).

A note on my second to last [commit](https://github.com/Mongey/terraform-provider-kafka/pull/286/commits/6fce0d2089d0eb7416112ab4c81fc6559d23322a): I've removed the logic to update the ACL saved in the state in the case of a *partial match*, it was still randomly causing the issue described in #285.
As stated before, I don't understand why it was implemented that way in the first place (considering equal two ACL with just ResourceName+Principal+Operation) and so I don't know what effect its removal could cause.

**Comment by jkemming** [comment]
Thanks for the fix! Apparently GitHub has changed it so that we'll now have to wait for Mongey to approve the workflow, otherwise the linter won't run...

On the matter partial matching:
I don't know its history either but it seems to have been introduced [here](https://github.com/Mongey/terraform-provider-kafka/pull/65/commits/25fcb41f4239b03700a164df9b5274797bc4e1c1#diff-96b426b500b05d82f278d18041bd6afa58f0412b2185bf38489b538e0f9920f6R127-R136). From the context of that PR I'm guessing it's so that you can change certain ACL properties (other than `ResourceName`, `Principal` and `Operation`) and have Terraform still recognize the resource in question.
Given that an ACL's identity as regards this Terraform provider is [defined as all its properties](https://github.com/Mongey/terraform-provider-kafka/blob/master/kafka/kafka_acls.go#L30), this seems logically impossible to me. The idea is that an existing ACL could have different properties from the one we're trying to create but still be the same, i.e. have the same identity - which means they must have the same properties.

I'd be interested to hear the authors' opinions on this since this would obviously change the provider's behavior regarding existing ACLs.

**Comment by xiaxuantan** [comment]
Hey friends, do you have any plans for cutting a release with this fix included in the near future? Ideally, we can have this in our production environment soon.

**Comment by Mongey** [comment]
@xiaxuantan I just pushed a new release [v0.5.2](https://github.com/Mongey/terraform-provider-kafka/releases/tag/v0.5.2)

**Pull request merged**
