### PR TITLE
AWS IAM authentication

### PR DESCRIPTION
**Pull request by errm**
AWS have now provided a library
https://github.com/aws/aws-msk-iam-sasl-signer-go that provides IAM authentication with MSK clusters.

This should be very similar to #242 in operation, but by using this library there is much less code to maintain here.

Let me know if you want me to add documentation and or tests around this?

### CODE REVIEW

**Comment by Mongey** [comment]
Looks good, thanks @errm . I'll merge this, but, it'd be good to get some tests / documentation around it too.

**Comment by cemo** [comment]
@Mongey Can you cut a release please?

**Comment by Mongey** [comment]
@cemo sure

**Comment by fmartinou** [comment]
Hi,

Is this implementation working with [AWS STS](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html)?

When I run Terraform from a CD pipeline, I have an `AccessKey`, a `SecretKey` and a `SecurityToken`.
How can I provide them to the provider to authenticate?

**Comment by cemo** [comment]
Please provide them as environment variable. ACCESS_KEY and SECRET_KEY

**Comment by fmartinou** [comment]
Thank you very much for the answer; I'll test tomorrow👍

Where can I find the possible environment variables regarding IAM auth?

Because usually, the "official" env vars are
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

It's not the case with the underlying library which is used?

**Comment by fmartinou** [comment]
I can answer myself.

The provider will load the AWS credentials using the [AWS SDK for Go](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/)

That means, you can use the regular env vars:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

You can also put your credentials in a `~/.aws/credentials` file
```
[default]
aws_access_key_id=XXX
aws_secret_access_key=YYY
aws_session_token=ZZZ
```

Please notice that:
1. the provider doesn't support named profiles; it would be a great enhancement.
2. the provider doesn't support to to set aws credentials through provider options; it would be very convenient (like the [aws provider does](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference))

**Comment by twcurrie** [comment]
Looks like there's a miss on updating the documentation here.

**Pull request merged**
